### ISSUE TITLE
Style the IDE

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#1]
Make the IDE look attractive
->Add Bootstrap Components
->Make a place for adding custom inputs
->Design the textarea (ie Editor Portion)

Currently the page has Minimal Design

**Comment by nutmegprince** [comment]
Hi there, I'd be happy to add some style to the page. However, I can see that there is already a pull request to add in bootstrap components so I'm figuring I will wait for that to be merged first.

**Comment by sirjan13** [comment]
Its merged you can start now :)

**Comment by nutmegprince** [comment]
on it, thanks!

**Comment by sirjan13** [comment]
Ya sure go for it.
Just be sure you have updated your fork somce the basic ide is added now :)
