### ISSUE TITLE
Making two separate buttons

### ISSUE THREAD

**Issue by udithishara** [Code-Fellas/ide#10]
Make two separate buttons for code Run and Submit

**Comment by sirjan13** [comment]
Are you working for this?

**Comment by udithishara** [comment]
yep, i've already did this, but before pushing im working on adding a .gitignore file, cause my phpStorm files are keep getting added when i do a `add .`

**Comment by sirjan13** [comment]
Sure GFI 👍

**Comment by udithishara** [comment]
aargh, I'm too sleepy to fix it now 🙈 
I've added the two button ( and dir `.idea` came with it, i'll fix it later )
