### ISSUE TITLE
Line Number Indexing

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#18]
As in any code editor introduce Line Numbers in the code Editor currently its just the text area .Indicate line numbers along the left side of the margin.

**Comment by udithishara** [comment]
[CodeMirror](http://codemirror.net/) would be perfect for this, it comes with more than just line numbers

If anyone wanna try this go ahead

**Comment by f0x52** [comment]
pull request #20

**Comment by Sanskar-Jain** [comment]
@f0x52 We sincerely appreciate your effort but this is not exactly what we are looking for.
Please refer to https://www.codechef.com/ide. This is how we want line indexing to be implemented here.

**Comment by schalkneethling** [comment]
Anyone actively working on this? If not, I am, happy to take it. Just let me know. Thanks!

**Comment by Sanskar-Jain** [comment]
@schalkneethling Go for it!

**Comment by schalkneethling** [comment]
@Sanskar-Jain So, if I integrate CodeMirror to replace the current simple text area, this will do the trick right. CodeMirror has a ton of features you can use, line numbers being only one of them. If that works for you, then I will go right ahead and get a PR ready. Thanks!

**Comment by Sanskar-Jain** [comment]
Yes, start working on it but make sure you don't change or disable any other working functionality.

**Comment by schalkneethling** [comment]
Pull request: https://github.com/Code-Fellas/ide/pull/27

**Comment by sirjan13** [comment]
closing #18 via #27
