### ISSUE TITLE
Toggle button to switch between themes

### ISSUE THREAD

**Issue by Sanskar-Jain** [Code-Fellas/ide#19]
Since this would be a generic IDE why not have a toggle button to toggle btw light and dark color schemes because not everyone is comfortable using dark and similarly for white

For now, add only functionality using two (dark/light) themes.

**Comment by RavinduHasithanjana** [comment]
HI i am working on the enhancement

**Comment by nutmegprince** [comment]
I have a light theme done in CSS, I'm setting up the jQuery to toggle.

**Comment by nutmegprince** [comment]
@RavinduHasithanjana just saw your pull request, I can switch over to your button once it's merged

**Comment by udithishara** [comment]
The Button is already there next to download button
