### ISSUE TITLE
Structure the page

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#2]
Give the page a well defined structure

**Comment by Puritanic** [comment]
What kind of structure do you need?

**Comment by sirjan13** [comment]
Currently the page just has a textarea as the editor. We are looking for a Code Editor which has a header have :
->a dropdown for selecting language
->Displaying current language
->A Full Screen Toggle
->an icon to download code

For reference you can refer to : https://www.codechef.com/ide  for an idea for the editor shld somewhat look like.Not the exact replica but its just a reference to get an essence of how the code editor Looks Like

**Comment by udithishara** [comment]
I'm working on this, i'll put up a PR tonight

**Comment by sirjan13** [comment]
Sure :)
