### ISSUE TITLE
Editor Refractor

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#5]
Currently the editor is a HTML Code Editor.What we want is a editor for various programming Languages so add a Dropdown for changing Languages,Displaying Current Language same as whats found in Sites like Codechef/Hackerrank/Hackerearth etc.

> NOTE: A PR without SCREENSHOTS showing the Changes wont be accepted

.

**Comment by manaswinidas** [comment]
Do you need frontend only?

**Comment by sirjan13** [comment]
Yes Currently we are Working only on Frontend Part of the Ide

**Comment by sirjan13** [comment]
For more information about design refer to my comment on issue #2

**Comment by manaswinidas** [comment]
Thank you!

**Comment by manaswinidas** [comment]
Is anyone working on this? I would be happy to work on this otherwise. Do you want all the languages found on HackerRank/CodeChef or anything specific?

**Comment by sirjan13** [comment]
@manaswinidas currently just keep C,C++,Python we will add others later on through scripts

**Comment by sirjan13** [comment]
Assigning You for this issue

**Comment by manaswinidas** [comment]
Thank you!

**Comment by sirjan13** [comment]
@manaswinidas plz proceed with your work after viewing the new design

**Comment by manaswinidas** [comment]
@sirjan13 Is the design updated? I can see a drop-down menu has already been added.

**Comment by sirjan13** [comment]
Yes the design is updated
