### ISSUE TITLE
Move Project Code In separate Files

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#6]
Currently all the Code consisting of CSS,JS is all in one file.Place it in different Files/folders appropriately.

**Comment by sparkle-sparkle** [comment]
I would like to help you with this. Are there specific conventions for the folder structure you have in mind?

**Comment by sparkle-sparkle** [comment]
Nvm, I can see that the project specific JS & CSS is all in the html file and need to be extracted to JS and CSS files.

**Comment by sirjan13** [comment]
Yes we have Folders for this already there just Move this in appropriate locations

**Comment by MAsifOfficial** [comment]
@sparkle-sparkle are you working on this?

**Comment by manaswinidas** [comment]
Hello, everyone, Is this issue resolved?

**Comment by sirjan13** [comment]
@manaswinidas @MAsifOfficial This is resolved now you all may take up other issues :)
