### ISSUE TITLE
Report Bugs/Open Issues for Enhancements

### ISSUE THREAD

**Issue by sirjan13** [Code-Fellas/ide#8]
Feel Free to open issues for Further Enhancements to the ide and to report Bugs.Appropriate labels would be added after Review.

**Comment by schalkneethling** [comment]
@sirjan13 Is this really appropriate for Hacktoberfest? I get that you are asking for feature enhancement and bug reports but, for someone that have never used the IDE, what are we looking for?

This is great in terms of getting people to manually test but, perhaps some more guidance would be appropriate?

**Comment by schalkneethling** [comment]
For example, is there a final version and a beta/dev version? If so, people can test for regressions as well as bugs.
